// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Persimmon.TestRunner")]
[assembly: AssemblyProductAttribute("Persimmon.TestAdapter")]
[assembly: AssemblyVersionAttribute("0.11.0")]
[assembly: AssemblyFileVersionAttribute("0.11.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Persimmon.TestRunner";
        internal const System.String AssemblyProduct = "Persimmon.TestAdapter";
        internal const System.String AssemblyVersion = "0.11.0";
        internal const System.String AssemblyFileVersion = "0.11.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
